### ISSUE TITLE
Improperly triggers mouseout when hovering a child inputs auto complete suggestion.

### ISSUE THREAD

**Issue by alastairjwright** [briancherne/jquery-hoverIntent#46] opened 2015-07-23 14:59 UTC
Like the r5 issue which would improperly trigger mouse out when entering a child input[type="text"]. Same issue except it happens when you hover over a chrome autocomplete suggestion for an input element.

Reference to old bug: "hoverIntent r5 suffers from a defect in Google Chrome that improperly triggers mouseout when entering a child input[type="text"] element. hoverIntent r6 uses the same mouseenter/mouseleave special events as jQuery's built-in hover, and jQuery 1.5.1 patched this issue. Thanks to Colin Stuart for tipping me off about this and for providing isolated code to demonstrate/test."

**Comment by usmonster** [comment] 2015-07-27 19:19
Thanks for reporting this, @alastairjwright! Are you using the tagged v1.8.1 version, or the version from the master branch? In what version(s) of Chrome have you seen this?

Can you please provide a simplified demo via jsFiddle/jsbin to help us investigate? Thanks again!

**Comment by alastairjwright** [comment] 2015-07-27 19:44
Yes this is using the most recent version of hover intent and the most recent version of chrome (44.0.2403.107).

Just click the input in the menu dropdown and hover one of the input suggestions by chrome. Note, if you're on a new browser the input field may not offer any past email address suggestions.
http://jsfiddle.net/alsweeet/9x1cnteh/

**Comment by usmonster** [comment] 2015-07-27 23:21
I'm not seeing any issue on my end. I am able to hover over the autofill suggestions, and the `out` handler is not called at any time.

To further help investigation, can you tell me what OS you're using? Also, can you make sure the issue you are experiencing doesn't manifest when you use jQuery's own `.hover()` method?

**Comment by alastairjwright** [comment] 2015-07-27 23:27
I am seeing the bug on Mac OS X Yosemite (10.10.5). Just tested on windows and the bug is not present.

**Comment by usmonster** [comment] 2015-07-27 23:33
Ah, that's a clue. I will try to take a look later in the week.

In the meantime, can you verify that this doesn't happen with normal `.hover()`, and can you also check this with the previous version(s) of hoverIntent to help identify when this issue appeared? (If you're feeling ambitious, you can maybe do a `git bisect`.. ;)

Thanks again for the quick feedback!

**Comment by usmonster** [comment] 2015-07-28 07:54
I took a look, and it also happens when using jQuery's `.hover()`: http://jsfiddle.net/9x1cnteh/2/

This seems to be a bug in Chrome on Mac, possibly this one: http://crbug.com/475366 . You can star the issue to get it more attention, though it looks like it's being worked on.

As this is not an issue in hoverIntent (and a workaround for a transient, low-impact bug seems unnecessary), I'll close the issue. Thanks yet again for your report!

**Closed by usmonster** 2015-07-28 07:54 UTC

**Comment by mdunnerstick** [comment] 2019-08-14 09:37
Is there going to big a fix for this?  I am having the same issue

**Comment by usmonster** [comment] 2019-08-14 13:44
Hello @mdunnerstick. Thanks for your comment! This issue was closed. If your'e experiencing something similar, please open a new issue with clear reproduction steps and a link to a demo (using JSFiddle, CodePen, or similar). Thanks!

**Comment by mdunnerstick** [comment] 2019-08-14 13:59
I made a new issue:
https://github.com/briancherne/jquery-hoverIntent/issues/75
