### ISSUE TITLE
Check over/out methods gracefully.

### ISSUE THREAD

**Issue by adjohnson916** [briancherne/jquery-hoverIntent#52] opened 2015-12-13 23:04 UTC
If either `out` or `over` methods aren't provided or aren't functions, can we not throw exceptions?

**Comment by roydukkey** [comment] 2015-12-13 23:33
Why would you want to throw exceptions? HoverIntent will work fine without declaring an `out` function. I might only understand throwing an exception when both `over` and `out` are omitted, but I think I'd much prefer to just see the plugin quickly continue. What are your concerns about the current behavior?

**Comment by adjohnson916** [comment] 2015-12-13 23:51
@roydukkey I said "can we not" as in, we are and shouldn't be - hence "gracefully" in title.
I'm seeing this exception when defining only an "over" method and not an "out" method in the options:

```
Uncaught TypeError: Cannot read property 'apply' of undefineddelay @ jquery.hoverIntent.js:82(anonymous function) @ jquery.hoverIntent.js:108
component.js:29 ok
```
with version 1.8.1 from Bower.

We should probably check that it's defined before attempting to call it here: https://github.com/briancherne/jquery-hoverIntent/blob/2790012922c1e4d1aee555a2ed9ead77b3c662cf/jquery.hoverIntent.js#L86

Other similar bugs may exist, e.g. https://github.com/briancherne/jquery-hoverIntent/blob/2790012922c1e4d1aee555a2ed9ead77b3c662cf/jquery.hoverIntent.js#L74

**Comment by usmonster** [comment] 2015-12-14 00:00
Hello! I'm closing this as a duplicate of #42, which was fixed in #51 and will be available in the upcoming release (or on the master branch now, if you want a preview).

Thanks for reporting the issue and for using the plugin!

**Closed by usmonster** 2015-12-14 00:00 UTC

**Comment by adjohnson916** [comment] 2015-12-14 00:03
@usmonster Thanks. I'm not sure I want `out` to default to `over`, I'd prefer a no-op, but it's better at least. What about when `over` is undefined, but `out` isn't - then what's the actual vs. expected behaviors?

**Comment by usmonster** [comment] 2015-12-14 08:45
@adjohnson916 An undefined `out` will default to `over` to remain consistent with jQuery's `hover` semantics. This was a correction to match the [documented behavior](http://rawgit.com/briancherne/jquery-hoverIntent/2d64837/jquery.hoverIntent.html) and will likely not change, since one is expected to pass an explicit `$.noop` in your use case.

As for the behavior when there is an `out` without an `over`, again, according to the documentation, `over` is a required parameter for hoverIntent. There may be a case for defaulting `over` to `$.noop` when the plugin is invoked with _an object_, though this kind of invocation is often a mistake that might otherwise go unnoticed. As such, the plugin does not check for nor attempt to handle this case, so the current fail-fast behavior is both expected and desired.

It's true that this is the only place where it differs in jQuery `.hover`'s behavior, but I believe this was a design choice considering this line in the docs:
> Note, nothing prevents you from sending [an empty function](https://api.jquery.com/jquery.noop/) as the `handlerIn` or `handlerOut` functions.

Hope this answer your questions!
